version: '3.8'

services:
  dlna-radio-streamer:
    build: .
    container_name: dlna-radio-streamer
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Europe/Warsaw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
