version: '3.8'

services:
  stream-to-dlna:
    build: .
    image: stream-to-dlna:latest
    container_name: stream-to-dlna
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Europe/Warsaw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"